### ISSUE TITLE
Check code validity even when no system was provided (where appropriate)

### ISSUE THREAD

**Issue by nir-r** [Outburn-IL/fume-community#131] opened 2024-12-19 06:20 UTC
In the attached example, if the ValueSet can by fully $expand(ed) AND no new values can be introduced (binding strength is "required") => validate code against it even when no system was provided AND raise a warning for lack of system.

![image](https://github.com/user-attachments/assets/853ea806-5753-466c-aef9-6c83825abe95)

**Comment by mechanik-daniel** [comment] 2024-12-25 21:32
Duplicate of #130

**Closed by mechanik-daniel** 2024-12-25 21:32 UTC
Labels: duplicate, enhancement, wontfix
